name: Deploy Static Site to Azure Blob

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload static site to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source ./web \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}
